# Generated by Django 4.2 on 2023-07-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_image_delete_imagequery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('clicks', models.IntegerField(default=0)),
                ('outputText', models.CharField(default='', max_length=200)),
                ('inputText', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
