# Generated by Django 4.2 on 2023-07-24 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
