# Generated by Django 4.2 on 2023-09-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_query_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
