# Generated by Django 4.2 on 2023-09-11 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='created_date',
            new_name='createdAt',
        ),
    ]
